languague: java
jdk: oraclejdk13
git:
  depth: 3
branches:
  only:
  - master
script:
- chmod +x ./gradlew
jobs:
  include:
  - stage: test
    script: "./gradlew test"
deploy:
  provider: heroku
  api_key:
    secure: HuuDyVNcK1B01Ts4cQY8wMKT2rpOZ1hCNWSaXWUvuwD6vu9Sxm95+iYaRHoR9K/1G2pMLSB5Qg6iMjBhtRPE+V4mXna6C0gIIOFDZDbxHhRFN+rqbxKRJCp2blApei203hJ7Uq4fiZwMBbpEovrht6nuMzfYYQv3v0axLrQvQoen3DqzjFLo9eCzxYuBdwJjQlQzl8K06L2VJIY5yNyMDuUOVg9qiL510BJD19Zba0cZ8wDfRBUZl1Vfb9RcLfU3XTZc8tVMhzBRTwHF8iiDbGbjaHx7nHJzbQvwJ41K4JyIit/Y8ggz2FoW2PHH1J/AtG2qRuFFKE2oKDDjS5rlW50Qhx4K7DL8zim3y+lZEEXCWwlhqgpdtXBvELdAWZMJuJ5XldHaUfy8mZGmyeLIhQhXuYXTbeMUiiyf/2w5BALjrhRKsv8U1JN2J4SKHN7ums0r9NVxMAODnubrhtTdAEwVMdgbn4aEtzUfFYua7ik+qV8aknELrRFB9vb4YRNRVQayRF0cmMRNi/pVfdgUSrYAjfFgHUWox/EYpP8uOtDGXS1E4Id0tNQV3HvYtota0vp7WaxraEw4RKc/ZUKWfk132NSOFa/bi3OmTXyF2EDRys0lqMc88sk4IeYq7gpqm9ge8Fv632FuhVRKEAWtaVFWmG7cF107+smAEStT46g=
  app: spring-boot-market
  on:
    repo: felagos/market
