# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: market

on:
  push:
    branches: [ master ]

jobs:  
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
  
    - name: Test
      run: ./gradlew test
      
  build-image:
    runs-on: ubuntu-latest
    name: build-image
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          USER: ${{ secrets.GIT_USER }}
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker login docker.pkg.github.com -u ${{ secrets.GIT_USER }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/${{ secrets.GIT_USER }}/market/market:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_PORT: ${{ secrets.APP_PORT }}
          EXPOSED_PORT: ${{ secrets.EXPOSED_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER_HOST }}
          key: ${{ secrets.KEY_HOST }}
          port: ${{ secrets.PORT_HOST }}
          envs: GIT_USER,GITHUB_TOKEN,APP_PORT,EXPOSED_PORT,DB_HOST,DB_NAME,DB_USER,DB_PASSWORD,JWT_EXPIRATION,JWT_KEY
          script: |
            docker login docker.pkg.github.com -u $GIT_USER -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/$GIT_USER/market/market:latest
            CONTAINER="$(docker ps --all --quiet --filter=name=market)"
            if [ -n "$CONTAINER" ]; then
              docker stop $CONTAINER && docker rm $CONTAINER
            fi
            docker run --restart unless-stopped --name market -d -p $EXPOSED_PORT:$APP_PORT \
            --env PORT=$APP_PORT \
            --env DB_HOST=$DB_HOST \
            --env DB_NAME=$DB_NAME \
            --env DB_USER=$DB_USER \
            --env DB_PASSWORD=$DB_PASSWORD \
            --env JWT_KEY=$JWT_KEY \
            --env JWT_EXPIRATION=$JWT_EXPIRATION \
            docker.pkg.github.com/$GIT_USER/market/market:latest
